### ISSUE TITLE
articleタグというものを使っていなかった

### ISSUE THREAD

**Issue by nka21** [nka21/techc-web-project-02#26]
脳死で`div`タグ書いてて、`article`タグというものを使えていなかった。。

マークアップ言語むずかしいねぇ、、。

https://developer.mozilla.org/ja/docs/Web/HTML/Element/article

**Comment by junya3** [comment]
@nka21 
articleはね…正直私もいまいちどういう使い方したらいいか実際わからないんだけどさ…
sectionとarticleの違いって意外とわかりにくいよね笑
リンクありがとうね！マークアップだけでも色々あるから難しいよね笑

正直今回のWebサイトはセクションをどう区切ればいいのかとか全くわからないからさ…。
結構適当になってしまっているところはあるけど一応設定していおいてもいいと思う！
やっぱ使ってみないとわからないこともあるからさ笑
