### ISSUE TITLE
tailwindcss カラー定義

### ISSUE THREAD

**Issue by nka21** [nka21/techc-web-project-02#4]
使う色
[Color Palette: #FAF7F0 #D8D2C2 #B17457 #4A4947 - Color Hunt](https://colorhunt.co/palette/faf7f0d8d2c2b174574a4947)

クラス名を考える

**Comment by junya3** [comment]
Class名：

primary-100 - #B17457
accent-100 - #D8D2C2
bg-100 - #FAF7F0
fc-black-100 - #4A4947
fc-white-100 - #FFFFFF
(fc = Font Color)

今後ホバー時の透明度や色指定が出てきたとき用に全て数字を割り当てておきます。
いかがでしょうか？

**Comment by nka21** [comment]
GPT-4oに聞いてみた。 
https://chatgpt.com/share/672cdb64-a1c0-800d-b4be-0c8336fee212

textやbgへのカラー設定をする時にこんな感じ
```
text-primary-100: #B17457
bg-accent-100: #D8D2C2
bg-base-100: #FAF7F0
text-black-100: #4A4947
```

これら３つの命名は綺麗でいいよね
`primary` `accent` `base`

`black`っていうクラスはあるんだけど、`black-100`とすることで被らずに使えるっぽい！
<img width="449" alt="image" src="https://github.com/user-attachments/assets/4dae2d0a-860d-4b31-a3bb-e83d29397ea5">

**Comment by junya3** [comment]
いいんじゃない？
プライマリだけそれテキストに使ってないからprimaryのままでいいかも

よければそれで設定しちゃおっか

**Comment by nka21** [comment]
toppageブランチがキリの良いところまで出来たらPR送ったあと、mainからブランチ切って作業して貰おうかな
