### ISSUE TITLE
プレゼン資料のコーダー欄を記入する

### ISSUE THREAD

**Issue by nka21** [nka21/techc-web-project-02#40]

**Comment by junya3** [comment]
<a href="https://docs.google.com/presentation/d/1SGICbuXMw7Eu_aCGMQmXnest4HWA0x5mQXcLjEhTigE/edit?usp=sharing">プレゼン資料</a>

**Comment by junya3** [comment]
@nka21 
まあ文書は変えるとしてこんな感じじゃないかな


## 良かった点

- コーダー間では意外と分担ができていた
- お互いカバーできてた気がする
- 新しいことにチャレンジできた（めっちゃ個人的）

## 反省点

- デザイナーさんとのコミュニケーションがあまりできていなかった
- 環境構築に時間をかけてしまった
- 結構お兄さんだよりだった

**Comment by nka21** [comment]
@junya3 
良いと思うけど、
反省点として、デザインの1px単位での調整をするべきだった。とか？あー、でもこれはあれかデザイン側か

考えてくれてありがとう！

**Comment by junya3** [comment]
@nka21 

統一されてない部分もあったし、わたしたち頑張ったほうだと思うよ！

いえいえ、それなりに整えてスライドに書いておくね！

**Comment by junya3** [comment]
なんか手伝えそうなことがあればお教え
